someStringOption: encrypted:noop!v:the-value
listOptions:
  - name: option1
    value: encrypted:noop!v:first-value
  - name: option2
    value: encrypted:noop!v:second-value
  - name: option3
    value: encrypted:noop!v:third-value