###
#
# On commit to master trigger a release which will trigger post-release jobs (build, bake and deploy)
#
###
name: Create Github Release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    name: Create Github Release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ARMORY_PLATFORM_GITHUB_PAT_TOKEN }}
    steps:
      - uses: armory-io/infra-github-actions/create-release@master
        with:
          project_type: go
          github_token: ${{ secrets.ARMORY_PLATFORM_GITHUB_PAT_TOKEN }}
