###
#
# On commit to master trigger a release which will trigger post-release jobs (build, bake and deploy)
#
###
name: Create Github Release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    name: Create Github Release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ARMORY_PLATFORM_GITHUB_PAT_TOKEN }}
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.4
        with:
          go-version: '1.19'

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure git for private modules
        run: git config --global url."https://x-access-token:${{ secrets.ARMORY_PLATFORM_GITHUB_PAT_TOKEN }}@github.com".insteadOf "https://github.com"

      - uses: armory-io/infra-github-actions/create-release@master
        with:
          project_type: go
          github_token: ${{ secrets.ARMORY_PLATFORM_GITHUB_PAT_TOKEN }}
          vault_addr: ${{ secrets.VAULT_ADDR }}
          vault_token: ${{ secrets.VAULT_TOKEN }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          sonar_host_url: ${{ secrets.SONAR_HOST_URL }}
          artifactory_user: ${{ secrets.ARTIFACTORY_USER }}
          artifactory_token: ${{ secrets.ARTIFACTORY_TOKEN }}
          go_version: '1.19'
